// Code generated by xo. DO NOT EDIT.

{{ $tableNameCamel := camelCase .Table.TableName -}}
{{- $shortName := shortName $tableNameCamel -}}

{{ $idType := "int" }}
{{- range .Table.Columns }}
    {{- if eq .ColumnName "id" }}
        {{- $idType = .GoType }}
    {{- end}}
{{- end -}}

package repo

import (
    sq "github.com/elgris/sqrl"
    "github.com/google/wire"
)

type I{{ $tableNameCamel }}Repository interface {
    I{{ $tableNameCamel }}RepositoryQueryBuilder
    
    Insert{{ $tableNameCamel }}(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}Create) (*table.{{ $tableNameCamel }}, error)
    Insert{{ $tableNameCamel }}WithSuffix(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}Create, suffix sq.Sqlizer) (*table.{{ $tableNameCamel }}, error)
    Insert{{ $tableNameCamel }}IdResult(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}Create, suffix sq.Sqlizer) (int64, error)

    Update{{ $tableNameCamel }}ByFields(ctx context.Context, id {{ $idType }}, {{ $shortName }} table.{{ $tableNameCamel }}Update) (*table.{{ $tableNameCamel }}, error)
    Update{{ $tableNameCamel }}(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}) (*table.{{ $tableNameCamel }}, error)
    
    Delete{{ $tableNameCamel }}(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}) error
    Delete{{ $tableNameCamel }}ById(ctx context.Context, id {{ $idType }}) (bool, error)
    
    FindAll{{ $tableNameCamel }}(ctx context.Context, {{ $shortName }} *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination) (*table.List{{ $tableNameCamel }}, error)
    FindAll{{ $tableNameCamel }}WithSuffix(ctx context.Context,{{ $shortName }} *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination, suffixes ...sq.Sqlizer) (*table.List{{ $tableNameCamel }}, error)

    {{- range .Indexes}}
        {{- if .IsUnique }}
        {{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}(ctx context.Context, 
            {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
        filter *table.{{ $tableNameCamel }}Filter) (table.{{ $tableNameCamel }}, error)
        
        {{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}WithSuffix(ctx context.Context, 
            {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
        filter *table.{{ $tableNameCamel }}Filter, suffixes ...sq.Sqlizer) (table.{{ $tableNameCamel }}, error)
        
        {{- else }}

        {{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}(ctx context.Context, 
            {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
        filter *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination) (*table.List{{ $tableNameCamel }}, error)
        
        {{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}WithSuffix(ctx context.Context, 
            {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
        filter *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination, suffixes ...sq.Sqlizer) (*table.List{{ $tableNameCamel }}, error)

        {{- end }}

    {{- end}}
}


type I{{ $tableNameCamel }}RepositoryQueryBuilder interface {
    FindAll{{ $tableNameCamel }}BaseQuery(ctx context.Context, filter *table.{{ $tableNameCamel }}Filter, fields string, suffix ...sq.Sqlizer) (*sq.SelectBuilder, error)
    AddPagination(ctx context.Context, qb *sq.SelectBuilder, pagination *internal.Pagination) (*sq.SelectBuilder, error)
}

type {{ $tableNameCamel }}Repository struct {
    DB internal.IDb
    QueryBuilder I{{ $tableNameCamel }}RepositoryQueryBuilder
}

type {{ $tableNameCamel }}RepositoryQueryBuilder struct {
}

var New{{ $tableNameCamel }}Repository = wire.NewSet(
    wire.Struct(new({{ $tableNameCamel }}Repository), "*"),
    wire.Struct(new({{ $tableNameCamel }}RepositoryQueryBuilder), "*"),
    wire.Bind(new(I{{ $tableNameCamel }}Repository), new(*{{ $tableNameCamel }}Repository)),
    wire.Bind(new(I{{ $tableNameCamel }}RepositoryQueryBuilder), new(*{{ $tableNameCamel }}RepositoryQueryBuilder)),
)

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) Insert{{ $tableNameCamel }}(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}Create) (*table.{{ $tableNameCamel }}, error) {
    return {{ $shortName }}r.Insert{{ $tableNameCamel }}WithSuffix(ctx, {{ $shortName }}, nil)
}

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) Insert{{ $tableNameCamel }}WithSuffix(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}Create, suffix sq.Sqlizer) (*table.{{ $tableNameCamel }}, error) {
    var err error
    
    id, err := {{ $shortName }}r.Insert{{ $tableNameCamel }}IdResult(ctx, {{ $shortName }}, suffix)
    if err != nil {
        return nil, err
    }
    new{{ $shortName }} := table.{{ $tableNameCamel }}{}
    qb := sq.Select("*").From(`{{ .Table.TableName }}`)

    qb.Where(sq.Eq{"`id`": id})
    err = {{ $shortName }}r.DB.Get(ctx, &new{{ $shortName }}, qb)

    if err != nil {
        return nil, err
    }
    return &new{{ $shortName }}, nil
}

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) Insert{{ $tableNameCamel }}IdResult(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}Create, suffix sq.Sqlizer) (int64, error) {
    var err error

    qb := sq.Insert("`{{ .Table.TableName }}`").Columns(
    
        {{- range .Table.Columns }}
        {{- if and (eq .IsGenerated false) (ne .ColumnName "id") (ne .ColumnName "created_at") (ne .ColumnName "updated_at") (ne .ColumnName "active")}}
            "`{{ .ColumnName }}`",
        {{- end}}
        {{- end }}
    ).Values(
        {{- range .Table.Columns }}
        {{- if and (eq .IsGenerated false) (ne .ColumnName "id") (ne .ColumnName "created_at") (ne .ColumnName "updated_at") (ne .ColumnName "active")}}
            {{ $shortName }}.{{ camelCase .ColumnName }},
        {{- end }}
        {{- end }}
    )
    if suffix != nil {
        suffixQuery, suffixArgs, suffixErr := suffix.ToSql()
        if suffixErr != nil {
            return 0, suffixErr
        }
        qb.Suffix(suffixQuery, suffixArgs...)
    }

    // run query
	res, err := {{ $shortName }}r.DB.Exec(ctx, qb)
	if err != nil {
		return 0, err
	}

    // retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return 0, err
	}

    return id, nil
} 

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) Update{{ $tableNameCamel }}ByFields(ctx context.Context, id {{ $idType }}, {{ $shortName }} table.{{ $tableNameCamel }}Update) (*table.{{ $tableNameCamel }}, error) {
    var err error 

    updateMap := map[string]interface{}{}
    {{- range .Table.Columns }}
    {{- if and (eq .IsGenerated false) (ne .ColumnName "id") (ne .ColumnName "created_at") (ne .ColumnName "updated_at") }}
        if ({{ $shortName }}.{{ camelCase .ColumnName }} != nil) {
            updateMap["`{{ .ColumnName }}`"] = *{{ $shortName }}.{{ camelCase .ColumnName }}
        }
    {{- end }}
    {{- end }}

    qb := sq.Update(`{{ .Table.TableName }}`).SetMap(updateMap).Where(sq.Eq{"`id`": id})

    _, err = {{ $shortName }}r.DB.Exec(ctx, qb)
    if err != nil {
        return nil, err
    }

    selectQb := sq.Select("*").From("`{{ $.Table.TableName }}`")

    selectQb = selectQb.Where(sq.Eq{"`id`": id})

    result := table.{{ $tableNameCamel }}{}
    err = {{ $shortName }}r.DB.Get(ctx, &result, selectQb)
    if err != nil {
        return nil, err
    }

    return &result, nil

}


func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) Update{{ $tableNameCamel }}(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}) (*table.{{ $tableNameCamel }}, error) {
    var err error

    // sql query
    qb := sq.Update("`{{ .Table.TableName }}`").SetMap(map[string]interface{}{
    {{- range .Table.Columns }}
        {{- if and (eq .IsGenerated false) (ne .ColumnName "id") (ne .ColumnName "created_at") (ne .ColumnName "updated_at") }}
        "`{{ .ColumnName }}`": {{ $shortName }}.{{ camelCase .ColumnName }},
        {{- end }}
    {{- end }}
    }).Where(sq.Eq{"`id`": {{ $shortName }}.Id})

    // run query
    _, err = {{ $shortName }}r.DB.Exec(ctx, qb)
    if err != nil {
        return nil, err
    }

    selectQb := sq.Select("*").From("`{{ .Table.TableName }}`")
    selectQb = selectQb.Where(sq.Eq{"`id`": {{ $shortName }}.Id})
    
    result := table.{{ $tableNameCamel }}{}
    err = {{ $shortName }}r.DB.Get(ctx, &result, selectQb)
    if err != nil {
        return nil, err
    }

    return &result, nil
}


func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) Delete{{ $tableNameCamel }}(ctx context.Context, {{ $shortName }} table.{{ $tableNameCamel }}) (error) {
    _, err := {{ $shortName }}r.Delete{{ $tableNameCamel }}ById(ctx, {{ $shortName }}.Id)
    return err
}


func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) Delete{{ $tableNameCamel }}ById(ctx context.Context, id {{ $idType }}) (bool, error) {
    var err error

    qb := sq.Update("`{{ .Table.TableName }}`").Set("active", false)

    qb = qb.Where(sq.Eq{"`id`": id})

    _, err = {{ $shortName }}r.DB.Exec(ctx, qb)
    if err != nil {
        return false, err
    } 
    return true, nil
}

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) FindAll{{ $tableNameCamel }}BaseQuery(ctx context.Context, filter *table.{{ $tableNameCamel }}Filter, fields string, suffixes ...sq.Sqlizer) (*sq.SelectBuilder, error) {
    return {{ $shortName }}r.QueryBuilder.FindAll{{ $tableNameCamel }}BaseQuery(ctx, filter, fields, suffixes...)
}

func ({{ $shortName }}r *{{ $tableNameCamel }}RepositoryQueryBuilder) FindAll{{ $tableNameCamel }}BaseQuery(ctx context.Context, filter *table.{{ $tableNameCamel }}Filter, fields string, suffixes ...sq.Sqlizer) (*sq.SelectBuilder, error) {
    var err error
    qb := sq.Select(fields).From("`{{ .Table.TableName }}`")
    if filter != nil {
        {{- range .Table.Columns }}
            {{- if eq .ColumnName "active" }}
                if filter.Active == nil {
                    if qb, err = internal.AddFilter(qb, "`{{ $.Table.TableName }}`.`active`", internal.FilterOnField{ {internal.Eq: true} }); err != nil {
                        return qb, err
                    }
                } else {
                    if qb, err = internal.AddFilter(qb, "`{{ $.Table.TableName }}`.`active`", filter.Active); err != nil {
                        return qb, err
                    }
                }
            {{- else }}
                if qb, err = internal.AddFilter(qb, "`{{ $.Table.TableName }}`.`{{ .ColumnName }}`", filter.{{ camelCase .ColumnName }}); err != nil {
                    return qb, err
                }
            {{- end }}
        {{- end }}
        qb, err = internal.AddAdditionalFilter(qb, filter.Wheres, filter.Joins, filter.LeftJoins, filter.GroupBys, filter.Havings)
        if err != nil {
            return qb, err
        }
    }
    {{- range .Table.Columns }}
        {{- if eq .ColumnName "active" }} else {
            if qb, err = internal.AddFilter(qb, "`{{ $.Table.TableName }}`.`active`", internal.FilterOnField{ {internal.Eq: true} }); err != nil {
                return qb, err
            }
        }
        {{- end }}
    {{- end }}

    for _, suffix := range suffixes {
        query, args, err := suffix.ToSql()
        if err != nil {
            return qb, err
        }
        qb.Suffix(query, args...)
    }
    return qb, nil
}

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) AddPagination(ctx context.Context, qb *sq.SelectBuilder, pagination *internal.Pagination) (*sq.SelectBuilder, error) {
    return {{ $shortName }}r.QueryBuilder.AddPagination(ctx, qb, pagination)
}

func ({{ $shortName }} *{{ $tableNameCamel }}RepositoryQueryBuilder) AddPagination(ctx context.Context, qb *sq.SelectBuilder, pagination *internal.Pagination) (*sq.SelectBuilder, error) {
    fields := []string {
        {{- range .Table.Columns }}   
            "{{ .ColumnName }}",
        {{- end }}
    }
    return internal.AddPagination(qb, pagination, "{{ .Table.TableName }}", fields)
}

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) FindAll{{ $tableNameCamel }}(ctx context.Context, filter *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination) (*table.List{{ $tableNameCamel }}, error) {
    return {{ $shortName }}r.FindAll{{ $tableNameCamel }}WithSuffix(ctx, filter, pagination)
}

func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) FindAll{{ $tableNameCamel }}WithSuffix(ctx context.Context, filter *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination, suffixes ...sq.Sqlizer) (*table.List{{ $tableNameCamel }}, error) {
    var list table.List{{ $tableNameCamel }}
    qb, err := {{ $shortName }}r.FindAll{{ $tableNameCamel }}BaseQuery(ctx, filter, "`{{ .Table.TableName }}`.*", suffixes...)
    if err != nil {
        return &list, err
    }
    qb, err = {{ $shortName }}r.AddPagination(ctx, qb, pagination)
    if err != nil {
        return &list, err
    }

    err = {{ $shortName }}r.DB.Select(ctx, &list.Data, qb)

    if err != nil {
        return &list, err
    }

    if pagination == nil || pagination.PerPage == nil || pagination.Page == nil {
        list.TotalCount = len(list.Data)
        return &list, nil
    }

    var listMeta internal.ListMetadata
    if qb, err = {{ $shortName }}r.FindAll{{ $tableNameCamel }}BaseQuery(ctx, filter, "COUNT(1) AS count"); err != nil {
        return &table.List{{ $tableNameCamel }}{}, err
    }
    if filter != nil && len(filter.GroupBys) > 0 {
        qb = sq.Select("COUNT(1) AS count").FromSelect(qb, "a")
    }
    err = {{ $shortName }}r.DB.Get(ctx, &listMeta, qb)

    list.TotalCount = listMeta.Count

    return &list, err
}

{{- range .Indexes}}
    {{- if .IsUnique }}
    func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) {{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}(ctx context.Context, 
        {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
    filter *table.{{ $tableNameCamel }}Filter) (table.{{ $tableNameCamel }}, error) {
        return {{ $shortName }}r.{{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}WithSuffix(ctx, 
        {{- range .Columns }} {{ camelCaseVar .ColumnName }},{{- end -}} filter)
    }

    func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) {{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}WithSuffix(ctx context.Context, 
        {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
    filter *table.{{ $tableNameCamel }}Filter, suffixes ...sq.Sqlizer) (table.{{ $tableNameCamel }}, error) {
        var err error

        // sql query
        qb, err := {{ $shortName }}r.FindAll{{ $tableNameCamel }}BaseQuery(ctx, filter, "`{{ $.Table.TableName }}`.*", suffixes...)
        if err != nil {
            return table.{{ $tableNameCamel }}{}, err
        }
        {{- range .Columns }}
            qb = qb.Where(sq.Eq{"`{{ $.Table.TableName }}`.`{{ .ColumnName }}`": {{ camelCaseVar .ColumnName }}})
        {{- end }}

        // run query
        {{ $shortName }} := table.{{ $tableNameCamel }}{}
        err = {{ $shortName }}r.DB.Get(ctx, &{{ $shortName }}, qb)
        if err != nil {
            return table.{{ $tableNameCamel }}{}, err
        }
        return {{ $shortName }}, nil
    }
    
    {{- else }}

    func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) {{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}(ctx context.Context, 
        {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
    filter *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination) (*table.List{{ $tableNameCamel }}, error) {
        return {{ $shortName }}r.{{ $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}WithSuffix(ctx, 
        {{- range .Columns }} {{ camelCaseVar .ColumnName }},{{- end -}} filter, pagination)
    }

    func ({{ $shortName }}r *{{ $tableNameCamel }}Repository) {{- $tableNameCamel }}By{{range .Columns}}{{camelCase .ColumnName}}{{end}}WithSuffix(ctx context.Context, 
        {{- range .Columns }} {{ camelCaseVar .ColumnName }} {{ .Column.GoType }},{{- end -}}
    filter *table.{{ $tableNameCamel }}Filter, pagination *internal.Pagination, suffixes ...sq.Sqlizer) (*table.List{{ $tableNameCamel }}, error) {

        var list table.List{{ $tableNameCamel }}
        // sql query
        qb, err := {{ $shortName }}r.FindAll{{ $tableNameCamel }}BaseQuery(ctx, filter, "`{{ $.Table.TableName }}`.*", suffixes...)
        if err != nil {
            return &list, err
        }
        {{- range .Columns }}
            qb = qb.Where(sq.Eq{"`{{ $.Table.TableName }}`.`{{ .ColumnName }}`": {{ camelCaseVar .ColumnName }}})
        {{- end }}

        if qb, err = {{ $shortName }}r.AddPagination(ctx, qb, pagination); err != nil {
            return &list, err
        }

        // run query
        if err = {{ $shortName }}r.DB.Select(ctx, &list.Data, qb); err != nil {
            return &list, err
        }

        if pagination == nil || pagination.PerPage == nil || pagination.Page == nil {
            list.TotalCount = len(list.Data)
            return &list, nil
        }

        var listMeta internal.ListMetadata
        if qb, err = {{ $shortName }}r.FindAll{{ $tableNameCamel }}BaseQuery(ctx, filter, "COUNT(1) AS count"); err != nil {
            return &list, err
        }
        if filter != nil && len(filter.GroupBys) > 0 {
            qb = sq.Select("COUNT(1) AS count").FromSelect(qb, "a")
        }
        {{- range .Columns }}
            qb = qb.Where(sq.Eq{"`{{ $.Table.TableName }}`.`{{ .ColumnName }}`": {{ camelCaseVar .ColumnName }}})
        {{- end }}
        if err = {{ $shortName }}r.DB.Get(ctx, &listMeta, qb); err != nil {
            return &list, err
        }

        list.TotalCount = listMeta.Count

        return &list, nil
    
        }
    {{- end }}

{{- end}}
