// Code generated by xo. DO NOT EDIT.

package rlts

import (
	"context"

	"github.com/google/wire"
	"github.com/ketan-10/training/backend/internal"
	"github.com/ketan-10/training/backend/xo_gen/repo"
	"github.com/ketan-10/training/backend/xo_gen/table"
)

type IAttendancesRltsRepository interface {

	// This Table Pointing to Other Table!!!, ManyToOne <- As Many records from other table can point to this table one record
	TrainingEventByFkTrainingEvent(ctx context.Context, obj *table.Attendances, filter *table.TrainingEventFilter) (*table.TrainingEvent, error)
	StudentsByFkStudent(ctx context.Context, obj *table.Attendances, filter *table.StudentsFilter) (*table.Students, error)

	//  Other Table Pointing to This Table!!!, OneToMany <- As This Table record can point to Multiple Other table record

}

type AttendancesRltsRepository struct {
	TrainingEventRepository repo.ITrainingEventRepository

	StudentsRepository repo.IStudentsRepository
}

var NewAttendancesRltsRepository = wire.NewSet(
	wire.Struct(new(AttendancesRltsRepository), "*"),
	wire.Bind(new(IAttendancesRltsRepository), new(*AttendancesRltsRepository)),
)

func (ar *AttendancesRltsRepository) TrainingEventByFkTrainingEvent(ctx context.Context, obj *table.Attendances, filter *table.TrainingEventFilter) (*table.TrainingEvent, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.TrainingEventFilter{}
	}

	filter.AddID(internal.Eq, obj.FkTrainingEvent)
	result, err := ar.TrainingEventRepository.FindAllTrainingEvent(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
func (ar *AttendancesRltsRepository) StudentsByFkStudent(ctx context.Context, obj *table.Attendances, filter *table.StudentsFilter) (*table.Students, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.StudentsFilter{}
	}

	filter.AddID(internal.Eq, obj.FkStudent)
	result, err := ar.StudentsRepository.FindAllStudents(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
