// Code generated by xo. DO NOT EDIT.

package rlts

import (
	"context"

	"github.com/google/wire"
	"github.com/ketan-10/training/backend/internal"
	"github.com/ketan-10/training/backend/xo_gen/repo"
	"github.com/ketan-10/training/backend/xo_gen/table"
)

type ITrainersRltsRepository interface {

	// This Table Pointing to Other Table!!!, ManyToOne <- As Many records from other table can point to this table one record
	UserByCreatedBy(ctx context.Context, obj *table.Trainers, filter *table.UserFilter) (*table.User, error)

	//  Other Table Pointing to This Table!!!, OneToMany <- As This Table record can point to Multiple Other table record
	TrainerTrainingMappingByFkTrainer(ctx context.Context, obj *table.Trainers, filter *table.TrainerTrainingMappingFilter, pagination *internal.Pagination) (*table.ListTrainerTrainingMapping, error)
}

type TrainersRltsRepository struct {
	UserRepository repo.IUserRepository

	TrainerTrainingMappingRepository repo.ITrainerTrainingMappingRepository
}

var NewTrainersRltsRepository = wire.NewSet(
	wire.Struct(new(TrainersRltsRepository), "*"),
	wire.Bind(new(ITrainersRltsRepository), new(*TrainersRltsRepository)),
)

func (tr *TrainersRltsRepository) UserByCreatedBy(ctx context.Context, obj *table.Trainers, filter *table.UserFilter) (*table.User, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.UserFilter{}
	}

	filter.AddID(internal.Eq, obj.CreatedBy)
	result, err := tr.UserRepository.FindAllUser(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
func (tr *TrainersRltsRepository) TrainerTrainingMappingByFkTrainer(ctx context.Context, obj *table.Trainers, filter *table.TrainerTrainingMappingFilter, pagination *internal.Pagination) (*table.ListTrainerTrainingMapping, error) {
	if obj == nil {
		return &table.ListTrainerTrainingMapping{}, nil
	}
	return tr.TrainerTrainingMappingRepository.TrainerTrainingMappingByFkTrainer(ctx, obj.ID, filter, pagination)
}
