package com.ketan.training.entity.enums;

public enum NotificationType {
    TRAINING_REQUEST_CREATED, TRAINING_REQUEST_APPROVED, TRAINING_REQUEST_REJECTED, TRAINING_CANCELLED,
    TRAINING_COMPLETED, TRAINING_SCHEDULED, TRAINING_DUE_ALERT, USER_REGISTRATION, FORGET_PASSWORD
}
