// Code generated by xo. DO NOT EDIT.

package xo_gen

import (
	"github.com/google/wire"
	"github.com/ketan-10/training/backend/xo_gen/repo"
	"github.com/ketan-10/training/backend/xo_gen/rlts"
)

var NewRepositorySet = wire.NewSet(

	repo.NewAttendancesRepository,
	rlts.NewAttendancesRltsRepository,
	repo.NewRegistrationsRepository,
	rlts.NewRegistrationsRltsRepository,
	repo.NewStudentsRepository,
	rlts.NewStudentsRltsRepository,
	repo.NewTrainerTrainingMappingRepository,
	rlts.NewTrainerTrainingMappingRltsRepository,
	repo.NewTrainersRepository,
	rlts.NewTrainersRltsRepository,
	repo.NewTrainingRepository,
	rlts.NewTrainingRltsRepository,
	repo.NewTrainingEventRepository,
	rlts.NewTrainingEventRltsRepository,
	repo.NewUserRepository,
	rlts.NewUserRltsRepository,
)
