// Code generated by xo. DO NOT EDIT.

package table

import (
	"database/sql"

	sq "github.com/elgris/sqrl"
	"github.com/ketan-10/training/backend/internal"
	"github.com/pkg/errors"
)

type TrainerTrainingMapping struct {
	ID              int          `json:"id" db:"id"`
	FkTrainingEvent int          `json:"fk_training_event" db:"fk_training_event"`
	FkTrainer       int          `json:"fk_trainer" db:"fk_trainer"`
	FkStudent       int          `json:"fk_student" db:"fk_student"`
	Active          bool         `json:"active" db:"active"`
	CreatedAt       sql.NullTime `json:"created_at" db:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at" db:"updated_at"`
}

type TrainerTrainingMappingFilter struct {
	ID              internal.FilterOnField
	FkTrainingEvent internal.FilterOnField
	FkTrainer       internal.FilterOnField
	FkStudent       internal.FilterOnField
	Active          internal.FilterOnField
	CreatedAt       internal.FilterOnField
	UpdatedAt       internal.FilterOnField
	Wheres          []sq.Sqlizer
	Joins           []sq.Sqlizer
	LeftJoins       []sq.Sqlizer
	GroupBys        []string
	Havings         []sq.Sqlizer
}

func (f *TrainerTrainingMappingFilter) NewFilter() interface{} {
	if f == nil {
		return &TrainerTrainingMappingFilter{}
	}
	return f
}

func (f *TrainerTrainingMappingFilter) TableName() string {
	return "`trainer_training_mapping`"
}

func (f *TrainerTrainingMappingFilter) ModuleName() string {
	return "trainer_training_mapping"
}

func (f *TrainerTrainingMappingFilter) IsNil() bool {
	return f == nil
}
func (f *TrainerTrainingMappingFilter) AddID(filterType internal.FilterType, v interface{}) {
	f.ID = append(f.ID, map[internal.FilterType]interface{}{filterType: v})
}
func (f *TrainerTrainingMappingFilter) AddFkTrainingEvent(filterType internal.FilterType, v interface{}) {
	f.FkTrainingEvent = append(f.FkTrainingEvent, map[internal.FilterType]interface{}{filterType: v})
}
func (f *TrainerTrainingMappingFilter) AddFkTrainer(filterType internal.FilterType, v interface{}) {
	f.FkTrainer = append(f.FkTrainer, map[internal.FilterType]interface{}{filterType: v})
}
func (f *TrainerTrainingMappingFilter) AddFkStudent(filterType internal.FilterType, v interface{}) {
	f.FkStudent = append(f.FkStudent, map[internal.FilterType]interface{}{filterType: v})
}
func (f *TrainerTrainingMappingFilter) AddActive(filterType internal.FilterType, v interface{}) {
	f.Active = append(f.Active, map[internal.FilterType]interface{}{filterType: v})
}
func (f *TrainerTrainingMappingFilter) AddCreatedAt(filterType internal.FilterType, v interface{}) {
	f.CreatedAt = append(f.CreatedAt, map[internal.FilterType]interface{}{filterType: v})
}
func (f *TrainerTrainingMappingFilter) AddUpdatedAt(filterType internal.FilterType, v interface{}) {
	f.UpdatedAt = append(f.UpdatedAt, map[internal.FilterType]interface{}{filterType: v})
}

func (f *TrainerTrainingMappingFilter) Where(v sq.Sqlizer) *TrainerTrainingMappingFilter {
	f.Wheres = append(f.Wheres, v)
	return f
}

func (f *TrainerTrainingMappingFilter) Join(j sq.Sqlizer) *TrainerTrainingMappingFilter {
	f.Joins = append(f.Joins, j)
	return f
}

func (f *TrainerTrainingMappingFilter) LeftJoin(j sq.Sqlizer) *TrainerTrainingMappingFilter {
	f.LeftJoins = append(f.LeftJoins, j)
	return f
}

func (f *TrainerTrainingMappingFilter) GroupBy(gb string) *TrainerTrainingMappingFilter {
	f.GroupBys = append(f.GroupBys, gb)
	return f
}

func (f *TrainerTrainingMappingFilter) Having(h sq.Sqlizer) *TrainerTrainingMappingFilter {
	f.Havings = append(f.Havings, h)
	return f
}

type TrainerTrainingMappingCreate struct {
	FkTrainingEvent int `json:"fk_training_event" db:"fk_training_event"`
	FkTrainer       int `json:"fk_trainer" db:"fk_trainer"`
	FkStudent       int `json:"fk_student" db:"fk_student"`
}

// TODO: We have to exclude AutoGenerated fields
// For now I am keeping it in, as not sure how it affects
type TrainerTrainingMappingUpdate struct {
	FkTrainingEvent *int  // fk_training_event
	FkTrainer       *int  // fk_trainer
	FkStudent       *int  // fk_student
	Active          *bool // active
}

// helper functions
func (u *TrainerTrainingMappingUpdate) ToTrainerTrainingMappingCreate() (res TrainerTrainingMappingCreate, err error) {
	if u.FkTrainingEvent != nil {
		res.FkTrainingEvent = *u.FkTrainingEvent
	} else {
		return res, errors.New("Value Can not be NULL")
	}
	if u.FkTrainer != nil {
		res.FkTrainer = *u.FkTrainer
	} else {
		return res, errors.New("Value Can not be NULL")
	}
	if u.FkStudent != nil {
		res.FkStudent = *u.FkStudent
	} else {
		return res, errors.New("Value Can not be NULL")
	}
	return res, nil
}

type ListTrainerTrainingMapping struct {
	TotalCount int
	Data       []TrainerTrainingMapping
}

func (l *ListTrainerTrainingMapping) GetAllID() []int {
	var res []int
	for _, item := range l.Data {
		res = append(res, item.ID)
	}
	return res
}
func (l *ListTrainerTrainingMapping) GetAllFkTrainingEvent() []int {
	var res []int
	for _, item := range l.Data {
		res = append(res, item.FkTrainingEvent)
	}
	return res
}
func (l *ListTrainerTrainingMapping) GetAllFkTrainer() []int {
	var res []int
	for _, item := range l.Data {
		res = append(res, item.FkTrainer)
	}
	return res
}
func (l *ListTrainerTrainingMapping) GetAllFkStudent() []int {
	var res []int
	for _, item := range l.Data {
		res = append(res, item.FkStudent)
	}
	return res
}
func (l *ListTrainerTrainingMapping) GetAllActive() []bool {
	var res []bool
	for _, item := range l.Data {
		res = append(res, item.Active)
	}
	return res
}
func (l *ListTrainerTrainingMapping) GetAllCreatedAt() []sql.NullTime {
	var res []sql.NullTime
	for _, item := range l.Data {
		res = append(res, item.CreatedAt)
	}
	return res
}
func (l *ListTrainerTrainingMapping) GetAllUpdatedAt() []sql.NullTime {
	var res []sql.NullTime
	for _, item := range l.Data {
		res = append(res, item.UpdatedAt)
	}
	return res
}

func (l *ListTrainerTrainingMapping) Filter(f func(item TrainerTrainingMapping) bool) (res ListTrainerTrainingMapping) {
	for _, item := range l.Data {
		if f(item) {
			res.Data = append(res.Data, item)
		}
	}
	res.TotalCount = len(res.Data)
	return res
}

func (l *ListTrainerTrainingMapping) Find(f func(item TrainerTrainingMapping) bool) (res TrainerTrainingMapping, found bool) {
	for _, item := range l.Data {
		if f(item) {
			return item, true
		}
	}
	return TrainerTrainingMapping{}, false
}

func (l *ListTrainerTrainingMapping) MapByFkStudent() (m map[int]ListTrainerTrainingMapping) {
	m = make(map[int]ListTrainerTrainingMapping)
	for _, item := range l.Data {
		list := m[item.FkStudent]
		list.Data = append(list.Data, item)

		m[item.FkStudent] = list
	}
	for k, v := range m {
		v.TotalCount = len(v.Data)
		m[k] = v
	}
	return m
}

func (l *ListTrainerTrainingMapping) MapByFkTrainer() (m map[int]ListTrainerTrainingMapping) {
	m = make(map[int]ListTrainerTrainingMapping)
	for _, item := range l.Data {
		list := m[item.FkTrainer]
		list.Data = append(list.Data, item)

		m[item.FkTrainer] = list
	}
	for k, v := range m {
		v.TotalCount = len(v.Data)
		m[k] = v
	}
	return m
}

func (l *ListTrainerTrainingMapping) MapByFkTrainingEvent() (m map[int]ListTrainerTrainingMapping) {
	m = make(map[int]ListTrainerTrainingMapping)
	for _, item := range l.Data {
		list := m[item.FkTrainingEvent]
		list.Data = append(list.Data, item)

		m[item.FkTrainingEvent] = list
	}
	for k, v := range m {
		v.TotalCount = len(v.Data)
		m[k] = v
	}
	return m
}

func (l *ListTrainerTrainingMapping) MapByID() (m map[int]TrainerTrainingMapping) {
	m = make(map[int]TrainerTrainingMapping, len(l.Data))
	for _, item := range l.Data {
		m[item.ID] = item
	}
	return m
}
