apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-static 
spec:
  selector:
    matchLabels:
      app: fe-static
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fe-static
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/elite-firefly-401018/internal-repo/static-fe-image:14
          name: fe-static
          ports:
            - containerPort: 80 
              name: fe-static

---
apiVersion: v1
kind: Service
metadata:
  name: fe 
spec:
  selector:
    app: fe-static 
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
