// Code generated by xo. DO NOT EDIT.

package xo_gen

import (
	"github.com/google/wire"
	"github.com/ketan-10/training/backend/xo_gen/repo"
	"github.com/ketan-10/training/backend/xo_gen/rlts"
)

var NewRepositorySet = wire.NewSet(

	repo.NewAttendancesRepository,
	rlts.NewAttendancesRltsRepository,
	repo.NewExternalResourcesRepository,
	rlts.NewExternalResourcesRltsRepository,
	repo.NewInternalResourcesRepository,
	rlts.NewInternalResourcesRltsRepository,
	repo.NewRegistrationsRepository,
	rlts.NewRegistrationsRltsRepository,
	repo.NewTrainerTrainingMappingRepository,
	rlts.NewTrainerTrainingMappingRltsRepository,
	repo.NewTrainingRepository,
	rlts.NewTrainingRltsRepository,
	repo.NewTrainingEventRepository,
	rlts.NewTrainingEventRltsRepository,
	repo.NewUserRepository,
	rlts.NewUserRltsRepository,
)
