// Code generated by xo. DO NOT EDIT.

package rlts

import (
	"context"

	"github.com/google/wire"
	"github.com/ketan-10/classroom/backend/internal"
	"github.com/ketan-10/classroom/backend/xo_gen/repo"
	"github.com/ketan-10/classroom/backend/xo_gen/table"
)

type ITrainingEventRltsRepository interface {

	// This Table Pointing to Other Table!!!, ManyToOne <- As Many records from other table can point to this table one record
	TrainingByFkTraining(ctx context.Context, obj *table.TrainingEvent, filter *table.TrainingFilter) (*table.Training, error)
	UserByCreatedBy(ctx context.Context, obj *table.TrainingEvent, filter *table.UserFilter) (*table.User, error)

	//  Other Table Pointing to This Table!!!, OneToMany <- As This Table record can point to Multiple Other table record
	AttendancesByFkTrainingEvent(ctx context.Context, obj *table.TrainingEvent, filter *table.AttendancesFilter, pagination *internal.Pagination) (*table.ListAttendances, error)
	TrainerTrainingMappingByFkTrainingEvent(ctx context.Context, obj *table.TrainingEvent, filter *table.TrainerTrainingMappingFilter, pagination *internal.Pagination) (*table.ListTrainerTrainingMapping, error)
}

type TrainingEventRltsRepository struct {
	TrainingRepository repo.ITrainingRepository

	UserRepository repo.IUserRepository

	AttendancesRepository repo.IAttendancesRepository

	TrainerTrainingMappingRepository repo.ITrainerTrainingMappingRepository
}

var NewTrainingEventRltsRepository = wire.NewSet(
	wire.Struct(new(TrainingEventRltsRepository), "*"),
	wire.Bind(new(ITrainingEventRltsRepository), new(*TrainingEventRltsRepository)),
)

func (ter *TrainingEventRltsRepository) TrainingByFkTraining(ctx context.Context, obj *table.TrainingEvent, filter *table.TrainingFilter) (*table.Training, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.TrainingFilter{}
	}

	filter.AddID(internal.Eq, obj.FkTraining)
	result, err := ter.TrainingRepository.FindAllTraining(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
func (ter *TrainingEventRltsRepository) UserByCreatedBy(ctx context.Context, obj *table.TrainingEvent, filter *table.UserFilter) (*table.User, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.UserFilter{}
	}

	filter.AddID(internal.Eq, obj.CreatedBy)
	result, err := ter.UserRepository.FindAllUser(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
func (ter *TrainingEventRltsRepository) AttendancesByFkTrainingEvent(ctx context.Context, obj *table.TrainingEvent, filter *table.AttendancesFilter, pagination *internal.Pagination) (*table.ListAttendances, error) {
	if obj == nil {
		return &table.ListAttendances{}, nil
	}
	return ter.AttendancesRepository.AttendancesByFkTrainingEvent(ctx, obj.ID, filter, pagination)
}
func (ter *TrainingEventRltsRepository) TrainerTrainingMappingByFkTrainingEvent(ctx context.Context, obj *table.TrainingEvent, filter *table.TrainerTrainingMappingFilter, pagination *internal.Pagination) (*table.ListTrainerTrainingMapping, error) {
	if obj == nil {
		return &table.ListTrainerTrainingMapping{}, nil
	}
	return ter.TrainerTrainingMappingRepository.TrainerTrainingMappingByFkTrainingEvent(ctx, obj.ID, filter, pagination)
}
